cvi.2.15.dtw_basic.workdaysByDay <- movingWindowWorkdaysByDay(windowSize = 2, clusterCount = 15, distanceMetric = "dtw_basic")
cvi.2.20.dtw_basic.workdaysByDay <- movingWindowWorkdaysByDay(windowSize = 2, clusterCount = 20, distanceMetric = "dtw_basic")
cvi.4.25.dtw_basic.workdaysByDay <- movingWindowWorkdaysByDay(windowSize = 4, clusterCount = 25, distanceMetric = "dtw_basic")

cvi.5.20.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 5, clusterCount = 20, distanceMetric = "dtw_basic")
cvi.4.20.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 4, clusterCount = 20, distanceMetric = "dtw_basic")
cvi.3.20.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
cvi.2.20.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 20, distanceMetric = "dtw_basic")

cvi.5.25.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 5, clusterCount = 25, distanceMetric = "dtw_basic")
cvi.4.25.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 4, clusterCount = 25, distanceMetric = "dtw_basic")
cvi.3.25.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 25, distanceMetric = "dtw_basic")
cvi.2.25.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 25, distanceMetric = "dtw_basic")

cvi.5.15.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 5, clusterCount = 15, distanceMetric = "dtw_basic")
cvi.4.15.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 4, clusterCount = 15, distanceMetric = "dtw_basic")
cvi.3.15.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 15, distanceMetric = "dtw_basic")
cvi.2.15.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 15, distanceMetric = "dtw_basic")


cvi.5.20.dtw_basic.weeks <- movingWindowWeeks(windowSize = 5, clusterCount = 20, distanceMetric = "dtw_basic")
cvi.4.20.dtw_basic.weeks <- movingWindowWeeks(windowSize = 4, clusterCount = 20, distanceMetric = "dtw_basic")
cvi.3.20.dtw_basic.weeks <- movingWindowWeeks(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
cvi.2.20.dtw_basic.weeks <- movingWindowWeeks(windowSize = 2, clusterCount = 20, distanceMetric = "dtw_basic")

cvi.5.25.dtw_basic.weeks <- movingWindowWeeks(windowSize = 5, clusterCount = 25, distanceMetric = "dtw_basic")
cvi.4.25.dtw_basic.weeks <- movingWindowWeeks(windowSize = 4, clusterCount = 25, distanceMetric = "dtw_basic")
cvi.3.25.dtw_basic.weeks <- movingWindowWeeks(windowSize = 3, clusterCount = 25, distanceMetric = "dtw_basic")
cvi.2.25.dtw_basic.weeks <- movingWindowWeeks(windowSize = 2, clusterCount = 25, distanceMetric = "dtw_basic")

cvi.5.15.dtw_basic.weeks <- movingWindowWeeks(windowSize = 5, clusterCount = 15, distanceMetric = "dtw_basic")
cvi.4.15.dtw_basic.weeks <- movingWindowWeeks(windowSize = 4, clusterCount = 15, distanceMetric = "dtw_basic")
cvi.3.15.dtw_basic.weeks <- movingWindowWeeks(windowSize = 3, clusterCount = 15, distanceMetric = "dtw_basic")
cvi.2.15.dtw_basic.weeks <- movingWindowWeeks(windowSize = 2, clusterCount = 15, distanceMetric = "dtw_basic")

cvi.5.20.gak.workdays <- movingWindowWorkdays(windowSize = 5, clusterCount = 20, distanceMetric = "gak")
cvi.4.20.gak.workdays <- movingWindowWorkdays(windowSize = 4, clusterCount = 20, distanceMetric = "gak")
cvi.3.20.gak.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "gak")
cvi.2.20.gak.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 20, distanceMetric = "gak")

cvi.5.20.lbi.workdays <- movingWindowWorkdays(windowSize = 5, clusterCount = 20, distanceMetric = "lbi")
cvi.4.20.lbi.workdays <- movingWindowWorkdays(windowSize = 4, clusterCount = 20, distanceMetric = "lbi")
cvi.3.20.lbi.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "lbi")
cvi.2.20.lbi.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 20, distanceMetric = "lbi")

cvi.5.20.dtw_lb.workdays <- movingWindowWorkdays(windowSize = 5, clusterCount = 20, distanceMetric = "dtw_lb")
cvi.4.20.dtw_lb.workdays <- movingWindowWorkdays(windowSize = 4, clusterCount = 20, distanceMetric = "dtw_lb")
cvi.3.20.dtw_lb.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_lb")
cvi.2.20.dtw_lb.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 20, distanceMetric = "dtw_lb")

cvi.8.20.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 8, clusterCount = 20, distanceMetric = "dtw_basic")
cvi.7.20.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 7, clusterCount = 20, distanceMetric = "dtw_basic")
cvi.6.20.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 6, clusterCount = 20, distanceMetric = "dtw_basic")
cvi.1.20.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 1, clusterCount = 20, distanceMetric = "dtw_basic")

cvi.3.11.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 11, distanceMetric = "dtw_basic")
cvi.2.11.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 11, distanceMetric = "dtw_basic")
cvi.3.12.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 12, distanceMetric = "dtw_basic")
cvi.2.12.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 12, distanceMetric = "dtw_basic")
cvi.3.13.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 13, distanceMetric = "dtw_basic")
cvi.2.13.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 13, distanceMetric = "dtw_basic")
cvi.3.14.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 14, distanceMetric = "dtw_basic")
cvi.2.14.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 14, distanceMetric = "dtw_basic")

cvi.3.16.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 16, distanceMetric = "dtw_basic")
cvi.2.16.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 16, distanceMetric = "dtw_basic")
cvi.3.17.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 17, distanceMetric = "dtw_basic")
cvi.2.17.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 17, distanceMetric = "dtw_basic")
cvi.3.18.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 18, distanceMetric = "dtw_basic")
cvi.2.18.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 18, distanceMetric = "dtw_basic")
cvi.3.19.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 19, distanceMetric = "dtw_basic")
cvi.2.19.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 19, distanceMetric = "dtw_basic")

cvi.3.21.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 21, distanceMetric = "dtw_basic")
cvi.2.21.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 21, distanceMetric = "dtw_basic")
cvi.3.22.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 22, distanceMetric = "dtw_basic")
cvi.2.22.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 22, distanceMetric = "dtw_basic")
cvi.3.23.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 23, distanceMetric = "dtw_basic")
cvi.2.23.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 23, distanceMetric = "dtw_basic")
cvi.3.24.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 24, distanceMetric = "dtw_basic")
cvi.2.24.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 24, distanceMetric = "dtw_basic")

cvi.3.26.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 26, distanceMetric = "dtw_basic")
cvi.2.26.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 26, distanceMetric = "dtw_basic")
cvi.3.27.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 27, distanceMetric = "dtw_basic")
cvi.2.27.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 27, distanceMetric = "dtw_basic")
cvi.3.28.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 28, distanceMetric = "dtw_basic")
cvi.2.28.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 28, distanceMetric = "dtw_basic")
cvi.3.29.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 29, distanceMetric = "dtw_basic")
cvi.2.29.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 29, distanceMetric = "dtw_basic")
cvi.3.30.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 3, clusterCount = 30, distanceMetric = "dtw_basic")
cvi.2.30.dtw_basic.workdays <- movingWindowWorkdays(windowSize = 2, clusterCount = 30, distanceMetric = "dtw_basic")

cvi.3.20.dtw_basic.workdays
t1 <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
t2 <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
t3 <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
t4 <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
t5 <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
t6 <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
t7 <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
t8 <- movingWindowWorkdays(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")

z1 <- movingWindowWorkdaysRemoveZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
z2 <- movingWindowWorkdaysRemoveZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
z3 <- movingWindowWorkdaysRemoveZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
z4 <- movingWindowWorkdaysRemoveZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
z5 <- movingWindowWorkdaysRemoveZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
z6 <- movingWindowWorkdaysRemoveZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
z7 <- movingWindowWorkdaysRemoveZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
z8 <- movingWindowWorkdaysRemoveZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")

n1 <- movingWindowWorkdaysRemoveBuildinZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
n2 <- movingWindowWorkdaysRemoveBuildinZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
n3 <- movingWindowWorkdaysRemoveBuildinZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
n4 <- movingWindowWorkdaysRemoveBuildinZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
n5 <- movingWindowWorkdaysRemoveBuildinZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
n6 <- movingWindowWorkdaysRemoveBuildinZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
n7 <- movingWindowWorkdaysRemoveBuildinZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
n8 <- movingWindowWorkdaysRemoveBuildinZ(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")

d1 <- movingWindowWorkdaysRemoveTime(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
d2 <- movingWindowWorkdaysRemoveTime(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
d3 <- movingWindowWorkdaysRemoveTime(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
d4 <- movingWindowWorkdaysRemoveTime(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
d5 <- movingWindowWorkdaysRemoveTime(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
d6 <- movingWindowWorkdaysRemoveTime(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
d7 <- movingWindowWorkdaysRemoveTime(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")
d8 <- movingWindowWorkdaysRemoveTime(windowSize = 3, clusterCount = 20, distanceMetric = "dtw_basic")

lapply(df, sd) / lapply(df, mean)
cvi.compare.basic
cvi.compare.nobuiltinz
cvi.compare.notime
